version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: ${API_REPOSITORY_URI}:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}