version: '3.8'

services:
  batch:
    build:
      context: .
      dockerfile: ./batch/Dockerfile
    image: ${BATCH_REPOSITORY_URI}:latest
    ports:
      - "8081:8081"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}