name: Deploy to ECS

on:
  push:
    branches:
      - dev  # dev 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI  # AWS CLI 설치
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials from environment variables
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        echo "AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY configured"
      
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t my-app:latest .
        docker tag my-app:latest <aws_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/my-app:latest

    - name: Push Docker image to ECR
      run: |
        docker push <aws_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/my-app:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster my-ecs-cluster --service my-ecs-service \
        --force-new-deployment --region $AWS_REGION
